### ISSUE TITLE
./gneasy-genkey.sh: line 4: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by piecam** [dadoug/gneasy-genkey#15]
HI,

Just had this to run and got this error? any hints? thanks.

./gneasy-genkey.sh: line 4: syntax error near unexpected token `newline'

**Comment by dadoug** [comment]
Can you give me the full command-line that you attempted to execute? (Don't for get to scrub/substitute any personally identifying information).

Can you give me the version number also?

Thanks for using this software! I'm glad for the opportunity to improve gneasy-genkey.

**Comment by piecam** [comment]
$ ./gneasy-genkey.sh "Peter Joe peter.joe@fccc.com"
./gneasy-genkey.sh: line 4: syntax error near unexpected token `newline'
./gneasy-genkey.sh: line 4:`<!DOCTYPE html>'

**Comment by piecam** [comment]
Hi dadoug, I just downloaded the version you have on this site. thanks for looking into it.

**Comment by dadoug** [comment]
Hi piecam,

The command-line syntax should be:

```
$ ./gneasy-genkey.sh "Peter Joe <peter.joe@fccc.com>"
```

Note the "<" and ">" sandwiching the email address.

You mention "the version ... on this site", do you know of this software being posted anywhere other than "https://github.com/dadoug/gneasy-genkey/"?

Thanks!

**Comment by piecam** [comment]
HI Dadoug,

I only bumped into this github site because reading Mr. English's post. I am not aware of other sites that may have this.

Here's a new run with your suggested,
peng@peng-MMLP3AP-00:~/Documents$ ./gneasy-genkey.sh "Peter Joe peter.joe@fccc.com"
./gneasy-genkey.sh: line 4: syntax error near unexpected token `newline'
./gneasy-genkey.sh: line 4:`<!DOCTYPE html>'

It looks still have some issue.
tks

**Comment by piecam** [comment]
peng@peng-MMLP3AP-00:~/Documents$ ./gneasy-genkey.sh "Peter Joe peter.joe@fccc.com"
./gneasy-genkey.sh: line 4: syntax error near unexpected token `newline'
./gneasy-genkey.sh: line 4:`<!DOCTYPE html>'

**Comment by piecam** [comment]
weird,

I have that <> in my copy/paste here, but, once "comment" button hit, it's gone !!!!! strange

**Comment by piecam** [comment]
![screenshot from 2015-10-18 14 32 02](https://github-cloud.s3.amazonaws.com/assets/10531131/10565690/07ca2606-75a5-11e5-8b81-e3d1642d18ae.png)

**Comment by dadoug** [comment]
Hhhhmmm ... okay, there may be a bug. 

Care to show me what "line 4" of your local copy of `gneasy-genkey.sh` looks like? (I'm thinking maybe a download error, or something.)

Thanks, again!

**Comment by piecam** [comment]
![screenshot from 2015-10-18 16 42 50](https://cloud.githubusercontent.com/assets/10531131/10566525/53a72260-75b7-11e5-84d5-5074f804594b.png)

**Comment by dadoug** [comment]
Ah. It looks like you're attempting to execute the webpage html as a bash script. Try starting with the [Download ZIP](https://github.com/dadoug/gneasy-genkey/archive/master.zip) button on the right of the main `gneasy-genkey.sh` github page.

**Comment by piecam** [comment]
ok, will try that. tks

**Comment by piecam** [comment]
HI Dadoug,
Here's output, with a few errors. Can you let me know the reason? It seems works most of it. 

thanks
peng@peng-MMLP3AP-00:~/Documents/gneasy-genkey-master$ ./gneasy-genkey.sh "Peter Kick peter.kick@f2f10.com"
egk: Consider using Tails https://tails.boum.org/.
egk: Creating new GnuPG keys for User-ID: Peter Kick peter.kick@f2f10.com
egk: Use a strong and memorable pass-phrase to protect your secret key.
egk: Generating key: master (certification) ...
egk: Generating key: signing ...
egk: Generating key: encryption ...
egk: Generating key: authentication ...
egk: Exported key:        0xD0664B8B4A728C45/public/public-key.asc
egk: Exported summary:    0xD0664B8B4A728C45/public/public-key-info.yaml
egk: Exported calendar:   0xD0664B8B4A728C45/public/expiration-reminder.ics
egk: Exported vcard:      0xD0664B8B4A728C45/public/contact.vcf
egk: Exported qr-code:    0xD0664B8B4A728C45/public/qr-uid-fpr.png
egk: Use a strong and memorable pass-phrase to protect your revocation certificate.
egk: ERROR: Failed to encrypt 0xD0664B8B4A728C45/private/revocation-cert.tgz
egk: ERROR: Failed to exporte revocation: failed
egk: Exported key:        0xD0664B8B4A728C45/private/master-secret-key.gpg
egk: Exported paperkey:   0xD0664B8B4A728C45/private/master-secret-paperkey.txt
egk: Exported key:        0xD0664B8B4A728C45/private/sub-secret-keys.gpg
egk: Removed master key:  0xD0664B8B4A728C45

**Comment by piecam** [comment]
https://github.com/harrisj/qrencoder/issues/11
https://github.com/fukuchi/libqrencode/issues/45

It was nice that your script use Qrencode to generate a few qrcode. Do you think it's good idea to generate a qrcode for secret key so that we can print out and save? The size of private part fits to qrencode well.

However, public part of key seems too big to fit in current qrencode. this public key is nice to be in qrcode to give to others. Any idea how soon we may have this ?

thanks

**Comment by dadoug** [comment]
It's not immediately obvious to me why you're getting the `Failed to encrypt` and/or `Failed to export` errors. Perhaps running with one of the `debug` flags would further illustrate the issue?

**Comment by dadoug** [comment]
I tried to strike a balance with the `paperkey` and `qrcode` output. Maybe some more qr-codes would be helpful?

**Comment by dadoug** [comment]
This thread gave a user some support: Closing
