### ISSUE TITLE
Debian-specific

### ISSUE THREAD

**Issue by jhmartin** [dadoug/gneasy-genkey#4]
`havegedStatus=$(dpkg --status haveged | grep Status)` results in the output
`./gneasy-genkey.sh: line 249: dpkg: command not found`
The script aborts here, probably due to `set -o errexit           ## exit on simple command fail
`

This precludes running the script on a host that does not support dpkg.

**Comment by dadoug** [comment]
Good catch, thanks!

Can you suggest a flavor independent way of checking for haveged? Using "type haveged &>/dev/null" didn't work correctly on the flavors to which I have access.

Since this is really only a user suggestion, I've commented out this section.
