### ISSUE TITLE
Pass in passphrase for automated testing

### ISSUE THREAD

**Issue by jhmartin** [dadoug/gneasy-genkey#6]
It would be useful for setting up an automated test harness if the key generation supported passing in a passphrase in a non-interactive fashion.

https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html discusses how this can be done.

**Comment by dadoug** [comment]
I agree. Such a feature was in my early drafts but didn't survive the development process.

I'm going to take this one step further and add a flag/option to pass in a passphrase file, even when one is not testing/debugging. To that end, I will close this issue and add another enhancement issue.

P.S. Thanks for the link. As far as I can tell, this method of key generation does not support multiple sub-keys. Bummer; such support would have made gneasy-genkey nearly trivial!

**Comment by dadoug** [comment]
This does not seem possible:
- The GnuPG option `--passphrase-file` requires the `--batch` option which precludes any state-machine interaction.
- The GnuPG [Unattended key generation](https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html) documentation indicates that neither generating multiple sub-keys nor adding sub-keys to an existing master key is supported.
